version: "3"

services:
  db:
    image: postgres:16
    restart: always
    volumes:
        - pgdata:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: passw0rd
        POSTGRES_USER: postgres
        POSTGRES_DB: testdb
    ports:
        - "5432:5432"

volumes:
    pgdata:
      driver: local

